.PHONY: clean All

All:
	@echo "----------Building project:[ task_1_waves - Debug ]----------"
	@cd "task_1_waves" && "$(MAKE)" -f  "task_1_waves.mk"
clean:
	@echo "----------Cleaning project:[ task_1_waves - Debug ]----------"
	@cd "task_1_waves" && "$(MAKE)" -f  "task_1_waves.mk" clean
