.PHONY: clean All

All:
	@echo "----------Building project:[ task_2_refactoring - Debug ]----------"
	@cd "task_2_refactoring" && "$(MAKE)" -f  "task_2_refactoring.mk"
clean:
	@echo "----------Cleaning project:[ task_2_refactoring - Debug ]----------"
	@cd "task_2_refactoring" && "$(MAKE)" -f  "task_2_refactoring.mk" clean
