.PHONY: clean All

All:
	@echo "----------Building project:[ task_2 - Debug ]----------"
	@cd "task_1" && "$(MAKE)" -f  "task_2.mk"
clean:
	@echo "----------Cleaning project:[ task_2 - Debug ]----------"
	@cd "task_1" && "$(MAKE)" -f  "task_2.mk" clean
